### ISSUE TITLE
Framework crashes when trying to read URL for bearnote file

### ISSUE THREAD

**Issue by cheesemaker** [shinyfrog/TextBundle#1] opened 2019-05-20 17:53 UTC
Currently it crashes on init on line 126 in TextBundleWrapper.m:
    NSFileWrapper *infoFileWrapper = [[textBundleFileWrapper fileWrappers] objectForKey:kTextBundleInfoFileName];

Error:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '-[NSFileWrapper fileWrappers] *** this method is only for directory type NSFileWrappers'

**Comment by cheesemaker** [comment] 2019-05-20 18:05
To be more clear, accessing the fileWrappers object in an app extension crashes. I have not been able to find any way around this.

**Comment by cheesemaker** [comment] 2019-05-20 21:57
So, upon further investigation, the bearnote object is a zipped file, not a bundled folder. I suppose unzipping is probably out of the scope of this project, but it probably should be modified so that it doesn't crash.

**Comment by matteorattotti** [comment] 2019-05-21 07:32
Hi there,

yes, the problem is that you're trying to open a textpack intestead of a textbundle file. 

As you've already guessed unzipping is out of scope, we didn't want to add a dependency to the library and also most application already have something to handle zip files.

The crash is not nice, we should probably prevent the opening of non textbundle files, I'll update the code to handle this and add a test.

Thanks for reporting :)

**Closed as completed** 2019-05-21 08:18 UTC
